INSERT INTO department (name)
VALUES  ('Administration'),
        ('Information Technology'),
        ('Operations'),
        ('Quality and Systems'),
        ('Finance'),
        ('Human Resources'),
        ('Industrial Relations'),
        ('Learning and Development'),
        ('Marketing'),
        ('Sales'),
        ('Research and Development'),
        ('Legal');

INSERT INTO role (title, salary, department_id)
VALUES  ('State Manager', 120000, 3),
        ('Quality and Systems Manager', 85000, 4),
        ('Area Manger', 65000, 3),
        ('Administration Officer', 35000, 1),
        ('IT Manager', 98000, 2),
        ('Business Analyst', 63000, 11),
        ('Youth Worker', 68000, 3),
        ('Case Manager', 86520, 3),
        ('Senior Quality Manager', 120000, 4),
        ('Finance Officer', 63000, 5),
        ('Finance Manager', 96300, 5),
        ('Commercial Analyst', 150000, 5),
        ('Trainer', 45250, 8),
        ('HR Manager', 77400, 6),
        ('Marketing and Comms Manager', 120000, 9),
        ('Sales Representative', 75000, 10),
        ('Sales Manager', 169000, 10),
        ('IR Manager', 250000, 7),
        ('Lawyer', 365000, 12);

INSERT INTO employee (first_name, last_name, role_id, manager_id) 
VALUES 
        ('Corey', 'Manning', 13, NULL),
        ('Hania', 'Oconnell', 1, 1),
        ('Lillia', 'Strickland', 6, 1),
        ('Conner', 'Paterson', 19, 1),
        ('Robbie', 'Harris', 7, 1),
        ('Amy', 'Hanson', 11, 1),
        ('Randy', 'Shaffer', 3, 1),
        ('Keagan', 'Baldwin', 4, 1),
        ('Sannah', 'Handley', 10, 6),
        ('Damon', 'Mann', 14, 4),
        ('Rochelle', 'Harrison', 6, 5),
        ('Neo', 'Lester', 8, 6),
        ('Tanner', 'Villa', 9, 8),
        ('Shayan', 'Lennon', 1, 7),
        ('Tayyab', 'Barry', 12, 4),
        ('Shannan', 'Corrigan', 19, 4),
        ('Samina', 'Woods', 9, 3),
        ('Jadine', 'Heaton', 7, 8),
        ('Shakeel', 'Farrow', 19, 9),
        ('Nana', 'Gilmour', 1, 4),
        ('Vivaan', 'Rhodes', 15, 5),
        ('Ashton', 'Morrow', 11, 5),
        ('Tyrese', 'Atkinson', 18, 4),
        ('Ruari', 'Jacobson', 19, 7),
        ('Vikram', 'Henry', 15, 7),
        ('Jozef', 'Douglas', 17, 4),
        ('Ifan', 'Donnelly', 17, 7),
        ('Ishmael', 'Baird', 5, 8),
        ('Zeynep', 'Parra', 12, 5),
        ('Yousuf', 'Kramer', 13, 4),
        ('Sabah', 'Finley', 19, 4),
        ('Kelsi', 'Boyd', 13, 5),
        ('Krzysztof', 'Stacey', 2, 5),
        ('Autumn', 'Leon', 7, 7),
        ('Juniper', 'English', 18, 7),
        ('Said', 'Brandt', 2, 6),
        ('Isabelle', 'Wynn', 19, 9),
        ('Jorden', 'Bartlett', 2, 4),
        ('Kayan', 'Head', 3, 7),
        ('Ann-Marie', 'Hatfield', 19, 3),
        ('Cynthia', 'Rollins', 15, 6),
        ('Kyra', 'Morton', 18, 4),
        ('Olivia', 'Tanner', 18, 7),
        ('Waleed', 'Frank', 18, 8),
        ('Oakley', 'Reeves', 5, 4),
        ('Jason', 'Benitez', 4, 6),
        ('Bonnie', 'Wells', 4, 8),
        ('Reyansh', 'Russell', 1, 3),
        ('Sadiyah', 'Padilla', 5, 6),
        ('Tierney', 'Clarke', 16, 7);

